### ISSUE TITLE
akai midimix crash when using potmeters

### ISSUE THREAD

**Issue by rdamen** [klingtnet/bitwig-extensions#2]
Hi,

I've tried using your midimix extension with Bitwig 2.4.3 and 2.5 on Linux but it crashes (with error -6) as soon as i touch a potentiometer.

Maybe I am doing something wrong and you can give me advice,
or maybe your extension only works with older Bitwig versions?

Thanks,
Ron

**Comment by rdamen** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: -6
        at com.bitwig.flt.control_surface.proxy.ControlSurfaceObject.returnArrayItem(SourceFile:416)
        at com.bitwig.flt.control_surface.proxy.UserControlBankObject.getControl(SourceFile:41)
        at net.klingt.akai.MidiHandler.lambda$handleUserControl$3(MidiHandler.java:81)
        at java.util.Optional.map(Optional.java:215)
        at net.klingt.akai.MidiHandler.handleUserControl(MidiHandler.java:81)
        at net.klingt.akai.MidiHandler.handleKnob(MidiHandler.java:75)
        at net.klingt.akai.MidiHandler.handleCC(MidiHandler.java:147)
        at net.klingt.akai.MidiHandler.midiReceived(MidiHandler.java:130)
        at Aix.ytz(SourceFile:199)
        at GcE.ytz(SourceFile:796)
        at GcE.ytz(SourceFile:59)
        at KyA.ytz(SourceFile:689)
        at pnD.ytz(SourceFile:97)
        at BuD.ytz(SourceFile:51)
        at LQk.ytz(SourceFile:33)
        at CbO.ytz(SourceFile:927)
        at pnD.pI(SourceFile:45)
        at KQh.ytz(SourceFile:213)
        at Iwv.kL(SourceFile:206)
        at jib.run(SourceFile:91)
        at Iwv.run(SourceFile:102)
```

**Comment by klingtnet** [comment]
Thank you for the MR, I will give it a look!
